version: '3'
networks:
  default:
    name: local
services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
      - "8080:8080" # Web UI port
    command:
      # Use HTTP for all containers.
      - --entrypoints.web.address=:80
      # Enables the web UI.
      - --api.insecure=true
      # Set container hostname to [service].local unless set in service config.
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.local`)
