version: '3'
networks:
  default:
    name: local
services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./config:/config/
    ports:
      - "443:443"
      - "8080:8080" # Web UI port
    command:
      # Use HTTPS for all containers.
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # Enables the web UI.
      - --api.insecure=true
      # Read config from the mounted volume.
      - --providers.file.directory=/config/
      # Set container hostname to [service].local unless set in service config.
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.local`)
